#pragma once

#include<QMainWindow>
#include "ui_transceiverFormFramework.h"
#include<QPushButton>
#include<QStackedWidget>
#include<marble/MarbleWidget.h>
#include<marble/AbstractFloatItem.h>
#include<QThread>
#include "IPBasedLocationRetriever.hpp"

namespace pylongps
{

/**
This class is the main window used with the pylon GPS 2.0 tranceiver.  It is written to use Qt4 with the Marble GIS library because that is what is currently available in the Ubuntu repositories.
*/
class transceiverGUI : public QMainWindow, public Ui::transceiverFormFramework
{
Q_OBJECT

public:

/**
This function initializes the class, connecting widgets, setting up the form generated by Qt designer and adding the components that the designer doesn't handle well.

@throw: This function can throw exceptions
*/
transceiverGUI();

public slots:
/**
This function toggles which page is displayed in the GUI.  If the current index is 0, it makes it 1 and vice versa.
*/
void toggleGUIPage();


protected:
};
















}
